<h1>Package Installation<h1>

In [23]:
# import os

# def install_packages():
#     packages = [
#         "pandas",
#         "nltk",
#         "scikit-learn",
#         "pyLDAvis",
#         "numpy",
#         "gensim",
#         "matplotlib",
#         "wordcloud",
#         "seaborn",
#     ]
#     for package in packages:
#         os.system(f"pip install {package}")

# install_packages()

<h1>Importing All Libraries</h1>

In [24]:
import nltk
nltk.download('wordnet')
nltk.download('vader_lexicon')
import re
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.decomposition import LatentDirichletAllocation, NMF
import pyLDAvis
import numpy as np
import time
from gensim.models import CoherenceModel
from gensim.corpora.dictionary import Dictionary
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import seaborn as sns
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\farha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\farha\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

<h1>Loading Data</h1>

In [25]:
# loading data

try:
    all_data = pd.read_csv('english_hate_speech.csv')
    all_data.head()
except Exception as e:
    print(f"Error loading data: {e}")

print("Shape of the data: ", all_data.shape) #inspecting the shape of the data

Shape of the data:  (14490, 4)

<h1>Data Preprocessing</h1>

<h3>Missing Values</h3>

In [26]:
# check missing value count
missing_values_count = all_data.isna().sum()
print(missing_values_count)
print("\n")
# As only 8 missing values, dropping these rows
all_data.dropna(subset=['clean_text'], inplace=True)

# checking missing values again
print("Checking missing value after dropping data")
missing_values_count = all_data.isna().sum()
print(missing_values_count)

Text          0
oh_label      0
Dataset       0
clean_text    8
dtype: int64


Checking missing value after dropping data
Text          0
oh_label      0
Dataset       0
clean_text    0
dtype: int64

<h3>Tokenizing the Clean Text Column</h3>

In [27]:
# Usage:
from nltk.tokenize import word_tokenize


all_data['tokenized_texts']=all_data['clean_text'].astype('string')
all_data['tokenized_texts']= all_data['clean_text'].apply(lambda x: word_tokenize(x))

all_data.head()

,Text,oh_label,Dataset,clean_text,tokenized_texts
0,I give permission for Wikipedia to use the ...,0.0,aggression_parsed_dataset_subset.csv,give permission Wikipedia use material Nancy S...,"[give, permission, Wikipedia, use, material, N..."
1,` October 2010 (UTC) :::::It does look that wa...,0.0,toxicity_parsed_dataset_subset.csv,October 2010 UTC look way merger sounds like C...,"[October, 2010, UTC, look, way, merger, sounds..."
2,RT @dcm81: #killerblondes ?? Have the producer...,0.0,twitter_parsed_dataset_subset.csv,RT dcm81 killerblondes producers lost plot eye...,"[RT, dcm81, killerblondes, producers, lost, pl..."
3,@ShaofHappiness COME SAY HI TO ME THIS EVENING...,0.0,twitter_parsed_dataset_subset.csv,ShaofHappiness COME SAY HI EVENING ILU,"[ShaofHappiness, COME, SAY, HI, EVENING, ILU]"
4,"@ManhattaKnight I mean he's gay, but he uses g...",1.0,cyberbullying_tweets_subset.csv,ManhattaKnight mean hes gay uses gendered slur...,"[ManhattaKnight, mean, hes, gay, uses, gendere..."

<h3>Lemmatize the Tokenized Texts Column</h3>

In [28]:
from nltk.stem import WordNetLemmatizer

# # nltk.download('wordnet')


#defining the object for Lemmatization
wordnet_lemmatizer = WordNetLemmatizer()

#defining the function for lemmatization
def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    # remove URLS and Numbers as well
    lemm_text = re.sub(r'[0-9]+|\bhttps?://\S+\b', '', " ".join(lemm_text))
    return lemm_text

all_data['lemmatized_text']=all_data['tokenized_texts'].apply(lambda x:lemmatizer(x))

all_data.head()

,Text,oh_label,Dataset,clean_text,tokenized_texts,lemmatized_text
0,I give permission for Wikipedia to use the ...,0.0,aggression_parsed_dataset_subset.csv,give permission Wikipedia use material Nancy S...,"[give, permission, Wikipedia, use, material, N...",give permission Wikipedia use material Nancy S...
1,` October 2010 (UTC) :::::It does look that wa...,0.0,toxicity_parsed_dataset_subset.csv,October 2010 UTC look way merger sounds like C...,"[October, 2010, UTC, look, way, merger, sounds...",October UTC look way merger sound like Cathol...
2,RT @dcm81: #killerblondes ?? Have the producer...,0.0,twitter_parsed_dataset_subset.csv,RT dcm81 killerblondes producers lost plot eye...,"[RT, dcm81, killerblondes, producers, lost, pl...",RT dcm killerblondes producer lost plot eye fa...
3,@ShaofHappiness COME SAY HI TO ME THIS EVENING...,0.0,twitter_parsed_dataset_subset.csv,ShaofHappiness COME SAY HI EVENING ILU,"[ShaofHappiness, COME, SAY, HI, EVENING, ILU]",ShaofHappiness COME SAY HI EVENING ILU
4,"@ManhattaKnight I mean he's gay, but he uses g...",1.0,cyberbullying_tweets_subset.csv,ManhattaKnight mean hes gay uses gendered slur...,"[ManhattaKnight, mean, hes, gay, uses, gendere...",ManhattaKnight mean he gay us gendered slur ma...

<h1>Feature Extraction</h1>

<h3>Bag of Words and TFIDF Counts of common words</h3>

In [29]:

# # Apply the BOW to all data

# def bag_of_words(data, text_column):
#     """
#     Creates a Bag-of-Words (BoW) representation from a given dataset.

#     Args:
#         data (pd.DataFrame): DataFrame containing the text data.
#         text_column (str): Name of the column containing the text data.

#     Returns:
#         tuple: A tuple containing the BoW matrix and the fitted CountVectorizer object.
#     """

#     # Select the text column
#     text_data = data[text_column]

#     # Create a CountVectorizer object
#     vectorizer = CountVectorizer()

#     # Transform the text into a BoW representation
#     bow_matrix = vectorizer.fit_transform(text_data)
#     # # Convert the sparse matrix to a dense array and then to a DataFrame
#     # bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

#     return bow_matrix, vectorizer

# BoW_all_data, vectorizer = bag_of_words(all_data,"lemmatized_text")

# print(BoW_all_data.toarray()[:5])

# # Access the vocabulary from the vectorizer
# vocabulary = vectorizer.get_feature_names_out()
# print(f"Vocabulary: {vocabulary[:10]}")  # Print the first 10 words

from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()
bow = count_vectorizer.fit_transform(all_data['lemmatized_text'])

count_array = bow.toarray()

features = count_vectorizer.get_feature_names_out()
BoW_all_data = pd.DataFrame(data=count_array, columns=features)

BoW_all_data.head()

,aa,aaa,aaan,aac,aah,aahhhh,aahil,aaj,aalaameenmercy,aaliya,...,平湖派,明治大君,明治天皇,本土,樊伯炎,治天下大王,竜龙,第版,署名の宣言,ﬂying
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(all_data['lemmatized_text'])

count_array = tfidf.toarray()

features = tfidf_vectorizer.get_feature_names_out()
TFIDF_all_data = pd.DataFrame(data=count_array, columns=features)

TFIDF_all_data.head()

,aa,aaa,aaan,aac,aah,aahhhh,aahil,aaj,aalaameenmercy,aaliya,...,平湖派,明治大君,明治天皇,本土,樊伯炎,治天下大王,竜龙,第版,署名の宣言,ﬂying
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0